version: '2'
services:
  mysql_db:
    image: mysql:latest
    volumes:
      #      Монтируем внешнюю папку для хранения данных
      - ./.mysql-data/db:/var/lib/mysql
      #      Инициализация БД из дампа из папки ./sqlinit при старте
    #      - ./sqlinit:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: fruzbuka_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678

  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  #  rabbit:
  #    hostname: rabbit
  #    image: rabbitmq:latest
  #    environment:
  #      - RABBITMQ_DEFAULT_USER=admin
  #      - RABBITMQ_DEFAULT_PASS=mypass
  #    ports:
  #      - "5672:5672"
  #    expose:
  #      - "5672"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  redis_data:
    driver: local